"""Mechanism maps from input configuration space to output joint space."""

from inequality_mechanisms.mechanisms.base import (
    Mechanism,
    MechanismRegistryError,
    clear_mechanism_registry,
    register_mechanism_type,
)
from inequality_mechanisms.mechanisms.branch_selection import (
    select_fourbar_monotonic_branch,
)
from inequality_mechanisms.mechanisms.equivalence import (
    BASELINE_LABELS,
    MATCHED_QUANTITY_TABLE,
    AxisMatchResult,
    baseline_label_for_matching_rule,
    baseline_label_for_mechanism,
    equivalence_summary_rows,
    is_derivable_equivalent_gearbox_dict,
    match_equivalent_gearbox,
    match_planar_fourbar_axis,
    verify_matched_graphs,
    verify_rms_match,
    verify_span_match,
    verify_tv_match,
)
from inequality_mechanisms.mechanisms.fourbar import IndependentFourBars, PlanarFourBar
from inequality_mechanisms.mechanisms.gearbox import (
    EquivalentGearbox,
    FixedRatioGearbox,
    UnitGearbox,
    equivalent_gearbox_matching_endpoints,
)
from inequality_mechanisms.mechanisms.monotonic import (
    MonotonicBox2D,
    MonotonicSector,
    find_monotonic_sectors,
    monotonic_box_for_independent_fourbars,
    open_axis_independent_fourbars,
    primary_monotonic_sector,
    unique_inverse_output,
)
from inequality_mechanisms.mechanisms.operating_branch import (
    AffineAxisInverse,
    BranchCertificate,
    BranchCertificationError,
    BranchInverseError,
    MonotoneTableAxisInverse,
    OperatingBranch,
    affine_operating_branch,
    certify_branch,
    equivalent_gearbox_branch,
    fixed_ratio_gearbox_branch,
    unit_gearbox_branch,
)
from inequality_mechanisms.mechanisms.output_mounting import (
    MountedOutputMechanism,
    mount_operating_branch,
)
from inequality_mechanisms.mechanisms.population import (
    CrankRockerPopulationSpec,
    follower_range,
    is_strict_crank_rocker,
    limits_from_fourbar_follower_ranges,
    output_space_from_fourbar_follower_ranges,
    sample_crank_rocker,
    sample_independent_crank_rockers,
)

__all__ = [
    "BASELINE_LABELS",
    "MATCHED_QUANTITY_TABLE",
    "AffineAxisInverse",
    "AxisMatchResult",
    "BranchCertificate",
    "BranchCertificationError",
    "BranchInverseError",
    "CrankRockerPopulationSpec",
    "EquivalentGearbox",
    "FixedRatioGearbox",
    "IndependentFourBars",
    "Mechanism",
    "MechanismRegistryError",
    "MonotoneTableAxisInverse",
    "MonotonicBox2D",
    "MonotonicSector",
    "MountedOutputMechanism",
    "OperatingBranch",
    "PlanarFourBar",
    "UnitGearbox",
    "affine_operating_branch",
    "baseline_label_for_matching_rule",
    "baseline_label_for_mechanism",
    "certify_branch",
    "clear_mechanism_registry",
    "equivalence_summary_rows",
    "equivalent_gearbox_branch",
    "equivalent_gearbox_matching_endpoints",
    "find_monotonic_sectors",
    "fixed_ratio_gearbox_branch",
    "follower_range",
    "is_derivable_equivalent_gearbox_dict",
    "is_strict_crank_rocker",
    "limits_from_fourbar_follower_ranges",
    "match_equivalent_gearbox",
    "match_planar_fourbar_axis",
    "monotonic_box_for_independent_fourbars",
    "mount_operating_branch",
    "open_axis_independent_fourbars",
    "output_space_from_fourbar_follower_ranges",
    "primary_monotonic_sector",
    "register_mechanism_type",
    "sample_crank_rocker",
    "sample_independent_crank_rockers",
    "select_fourbar_monotonic_branch",
    "unique_inverse_output",
    "unit_gearbox_branch",
    "verify_matched_graphs",
    "verify_rms_match",
    "verify_span_match",
    "verify_tv_match",
]
