"""Fail-closed output path guards for Sprint V3.6C artifacts.

V3.6C may write only under ``results/v3_review/v3_6c_planar2r_closeout/``.
Frozen V3.6 / V3.6B / provisional V3.7 packages under ``results/v3_review/``
must not be overwritten or regenerated by the closeout exporter.
"""

from __future__ import annotations

from pathlib import Path

# Repo root: src/inequality_mechanisms/audits/artifact_freeze.py -> parents[3]
REPO_ROOT = Path(__file__).resolve().parents[3]

V3_6C_ALLOWED_PACKAGE = "v3_6c_planar2r_closeout"
V3_6C_ALLOWED_OUTPUT_REL = Path("results") / "v3_review" / V3_6C_ALLOWED_PACKAGE

# Explicit frozen packages named by ACTIVE_SPRINT / V3.6C decisions.
FROZEN_EXPLICIT_PACKAGES: frozenset[str] = frozenset(
    {
        "v3_6_free_space",
        "v3_6_free_space_v2",
        "v3_6b_planar2r_visual_audit",
        "v3_7_3r_free_space",
    }
)


def allowed_v3_6c_output_root() -> Path:
    """Absolute allowed V3.6C closeout output root."""
    return (REPO_ROOT / V3_6C_ALLOWED_OUTPUT_REL).resolve()


def _is_under(path: Path, parent: Path) -> bool:
    path_r = path.resolve()
    parent_r = parent.resolve()
    return path_r == parent_r or parent_r in path_r.parents


def _review_package_name(path: Path) -> str | None:
    """Return the top-level package name under ``results/v3_review/``, if any."""
    review = (REPO_ROOT / "results" / "v3_review").resolve()
    try:
        rel = path.resolve().relative_to(review)
    except ValueError:
        return None
    if not rel.parts:
        return None
    return rel.parts[0]


def is_frozen_v3_review_package(name: str) -> bool:
    """Return True if ``name`` is a frozen ``results/v3_review/`` package.

    Matches explicit frozen packages and directory names under the prefixes
    ``v3_6_*``, ``v3_6b_*``, and ``v3_7_*``, excluding the V3.6C closeout
    package ``v3_6c_planar2r_closeout``.
    """
    if name == V3_6C_ALLOWED_PACKAGE:
        return False
    if name in FROZEN_EXPLICIT_PACKAGES:
        return True
    if name.startswith("v3_6b_") or name.startswith("v3_7_"):
        return True
    # ``v3_6_*`` but not ``v3_6c_*`` (closeout and any future v3_6c siblings).
    if name.startswith("v3_6_") and not name.startswith("v3_6c_"):
        return True
    return False


def assert_v3_6c_output_allowed(path: Path) -> Path:
    """Resolve ``path`` and assert it is under the V3.6C closeout output root.

    Parameters
    ----------
    path :
        Candidate output directory (absolute or relative).

    Returns
    -------
    pathlib.Path
        Resolved absolute path when the write is allowed.

    Raises
    ------
    ValueError
        If ``path`` is under a frozen ``v3_6_*`` / ``v3_6b_*`` / ``v3_7_*``
        package or is otherwise outside the allowed closeout root.
    """
    resolved = Path(path).expanduser().resolve()
    allowed = allowed_v3_6c_output_root()
    if _is_under(resolved, allowed):
        return resolved

    package = _review_package_name(resolved)
    if package is not None and is_frozen_v3_review_package(package):
        raise ValueError(
            f"Refusing to write into frozen V3 evidence package {package!r} "
            f"at {resolved}. V3.6C may write only under {allowed}."
        )

    raise ValueError(
        f"V3.6C output path {resolved} is not under the allowed closeout "
        f"root {allowed}. Frozen packages under results/v3_review/ "
        f"(v3_6_*, v3_6b_*, v3_7_*) must not be overwritten."
    )


__all__ = [
    "FROZEN_EXPLICIT_PACKAGES",
    "REPO_ROOT",
    "V3_6C_ALLOWED_OUTPUT_REL",
    "V3_6C_ALLOWED_PACKAGE",
    "allowed_v3_6c_output_root",
    "assert_v3_6c_output_allowed",
    "is_frozen_v3_review_package",
]
